edit systax

diff --git a/.github/workflows/test_sh.yaml b/.github/workflows/test_sh.yaml
--- a/.github/workflows/test_sh.yaml
+++ b/.github/workflows/test_sh.yaml
@@ -42,6 +42,10 @@ env:
 # A workflow run is made up of one or more jobs that can run sequentially or in parallel
 # The jobs are all run in independent environments. Here we will run a separate job
 # for each of the test suites specified in the matrix below.
+
+# This workflow calls build_image_sh.yaml workflow passing the specified
+# The Job Trigger and Download image from GitHub Artifact 
+# branches as inputs
 jobs:
   trigger-build-image:
     uses: ./.github/workflows/build_image_sh.yaml
@@ -69,9 +73,13 @@ jobs:
         id: load-image
         run: |
           IMAGE=$(gzip -dc docker-image/*.tar.gz | docker load | cut -d ' ' -f 3)
+          if [[ $? -ne 0 ]]; then
+              echo "Failed to load Docker image"
+              exit 1
+          fi
           echo "Loaded Image: $IMAGE"
           echo "image_id=$IMAGE" >> $GITHUB_OUTPUT
-
+      
   # Print out some stuff about the test environment
   image-sanity-checks:
     runs-on: [self-hosted, "${{ inputs.platform }}"]
@@ -93,7 +101,7 @@ jobs:
   # Run the tests for each repo in parallel in a test container
   run-tests:
     runs-on: [self-hosted, "${{ inputs.platform }}"]
-    needs: [build-test-image, image-sanity-checks]
+    needs: [download-image, image-sanity-checks]
     timeout-minutes: 540
     strategy:
       fail-fast: false
@@ -106,72 +114,72 @@ jobs:
           test_contexts: ${{ inputs.test_contexts }}
           pytest_options: ${{ inputs.pytest_options }}
         run: |
-          mkdir -p reports/xfields
-          docker run --rm --gpus all \
-            --env XOBJECTS_TEST_CONTEXTS="${test_contexts}" \
-            --env PYTEST_ADDOPTS="${pytest_options}" \
-            -v $PWD/reports/xfields:/opt/reports:Z \
-            ${image_id} \
-            /opt/run_tests.sh /opt/xsuite/xfields/tests | tee reports/xfields/results.txt
-
+            mkdir -p reports/${{ matrix.test-suite }}
+            docker run --rm --gpus all \
+              --env XOBJECTS_TEST_CONTEXTS="${test_contexts}" \
+              --env PYTEST_ADDOPTS="${pytest_options}" \
+              -v $PWD/reports/${{ matrix.test-suite }}:/opt/reports:Z \
+              ${image_id} \
+              /opt/run_tests.sh /opt/xsuite/${{ matrix.test-suite }}/tests | tee reports/${{ matrix.test-suite }}/results.txt
+      
       - name: List report files
         run: |
-          echo "Listing files in reports/${{ matrix.test-suite }}:"
-          ls -lah reports/${{ matrix.test-suite }}
+            echo "Listing files in reports/${{ matrix.test-suite }}:"
+            ls -lah reports/${{ matrix.test-suite }}
 
       - name: Extract Errors and Summarize in Markdown
         run: |
-          echo "## Test Summary" ${{ matrix.test-suite }}>> $GITHUB_STEP_SUMMARY
-          results_file="reports/${{ matrix.test-suite }}/results.txt"
-            if [ -f "$results_file" ]; then
-              echo "Results file found, processing..."
+            echo "## Test Summary" ${{ matrix.test-suite }}>> $GITHUB_STEP_SUMMARY
+            results_file="reports/${{ matrix.test-suite }}/results.txt"
+              if [ -f "$results_file" ]; then
+                echo "Results file found, processing..."
 
-              sed -i -e 's/\x1b\[[0-9;]*m//g' -e 's/^> /\\> /g' $results_file
-            
-              passed=$(grep -c PASSED $results_file || true)
-              failed=$(grep "FAILED.*xsuite" $results_file | grep -P 'FAILED.* - ' | sed -E 's/.*\] (.*::[^ ]+).* - .*/\1/' | sort | uniq | wc -l)
-              skipped=$(grep -c SKIPPED $results_file || true)
+                sed -i -e 's/\x1b\[[0-9;]*m//g' -e 's/^> /\\> /g' $results_file
               
-              echo "| Result | Number |" >> $GITHUB_STEP_SUMMARY
-              echo "|--------|-------|" >> $GITHUB_STEP_SUMMARY
-              echo "| Passed ✅| $passed |" >> $GITHUB_STEP_SUMMARY
-              echo "| Failed ❌| $failed |" >> $GITHUB_STEP_SUMMARY
-              echo "| Skipped ⏭️| $skipped |" >> $GITHUB_STEP_SUMMARY
+                passed=$(grep -c PASSED $results_file || true)
+                failed=$(grep "FAILED.*xsuite" $results_file | grep -P 'FAILED.* - ' | sed -E 's/.*\] (.*::[^ ]+).* - .*/\1/' | sort | uniq | wc -l)
+                skipped=$(grep -c SKIPPED $results_file || true)
+                
+                echo "| Result | Number |" >> $GITHUB_STEP_SUMMARY
+                echo "|--------|-------|" >> $GITHUB_STEP_SUMMARY
+                echo "| Passed ✅| $passed |" >> $GITHUB_STEP_SUMMARY
+                echo "| Failed ❌| $failed |" >> $GITHUB_STEP_SUMMARY
+                echo "| Skipped ⏭️| $skipped |" >> $GITHUB_STEP_SUMMARY
 
-              if [ $failed -ne 0 ]; then
-                echo "### 🔴 Failed Tests" >> $GITHUB_STEP_SUMMARY
-                grep "FAILED.*xsuite" $results_file | grep -P 'FAILED.* - ' | sed -E 's/.*\] (.*::[^ ]+).* - (.*)/\1 - \2/' | sort | uniq | while read -r failure; do
-                  echo "- $failure" >> $GITHUB_STEP_SUMMARY
-                  
-                  echo "<details><summary>Click here to view the error details</summary><p>" >> $GITHUB_STEP_SUMMARY
-                  echo '```'
+                if [ $failed -ne 0 ]; then
+                  echo "### 🔴 Failed Tests" >> $GITHUB_STEP_SUMMARY
+                  grep "FAILED.*xsuite" $results_file | grep -P 'FAILED.* - ' | sed -E 's/.*\] (.*::[^ ]+).* - (.*)/\1 - \2/' | sort | uniq | while read -r failure; do
+                    echo "- $failure" >> $GITHUB_STEP_SUMMARY
+                    
+                    echo "<details><summary>Click here to view the error details</summary><p>" >> $GITHUB_STEP_SUMMARY
+                    echo '```'
 
-                  echo "Debug: Failure detail extraction for $failure"
-                  test_name=$(echo "$failure" | sed -E 's/.*::([^\-]+).* - .*/\1/' | sed -E 's/\x1b\[[0-9;]*m//g' )
-                  test_name=$(echo "$test_name" | sed 's/[][]/\\&/g')
-                  echo "Debug: Looking for start of error details for $test_name"
-                  error_start_line=$(grep -n "____________________ ${test_name} ____________________" $results_file | cut -d: -f1)
-                  echo "Debug: Start line found at $error_start_line"
-                  error_end_line=$(tail -n +$((error_start_line + 1)) $results_file | grep -nm 1 "^-.*Captured stdout call.*-$" | cut -d: -f1)
-                  if [[ ! -z "$error_start_line" ]]; then
+                    echo "Debug: Failure detail extraction for $failure"
+                    test_name=$(echo "$failure" | sed -E 's/.*::([^\-]+).* - .*/\1/' | sed -E 's/\x1b\[[0-9;]*m//g' )
+                    test_name=$(echo "$test_name" | sed 's/[][]/\\&/g')
+                    echo "Debug: Looking for start of error details for $test_name"
+                    error_start_line=$(grep -n "____________________ ${test_name} ____________________" $results_file | cut -d: -f1)
+                    echo "Debug: Start line found at $error_start_line"
                     error_end_line=$(tail -n +$((error_start_line + 1)) $results_file | grep -nm 1 "^-.*Captured stdout call.*-$" | cut -d: -f1)
-                    if [[ ! -z "$error_end_line" ]]; then
-                        absolute_error_end_line=$((error_start_line + error_end_line - 1))
-                        echo "Debug: End line found at $absolute_error_end_line"
-                        sed -n "${error_start_line},${absolute_error_end_line}p" $results_file | sed 's/^>/\\>/' >> $GITHUB_STEP_SUMMARY
+                    if [[ ! -z "$error_start_line" ]]; then
+                      error_end_line=$(tail -n +$((error_start_line + 1)) $results_file | grep -nm 1 "^-.*Captured stdout call.*-$" | cut -d: -f1)
+                      if [[ ! -z "$error_end_line" ]]; then
+                          absolute_error_end_line=$((error_start_line + error_end_line - 1))
+                          echo "Debug: End line found at $absolute_error_end_line"
+                          sed -n "${error_start_line},${absolute_error_end_line}p" $results_file | sed 's/^>/\\>/' >> $GITHUB_STEP_SUMMARY
+                      fi
                     fi
-                  fi
-                  echo '```' 
-                  echo "</p></details>" >> $GITHUB_STEP_SUMMARY
-                done
+                    echo '```' 
+                    echo "</p></details>" >> $GITHUB_STEP_SUMMARY
+                  done
+                fi
+              else
+                echo "No test results found." >> $GITHUB_STEP_SUMMARY
               fi
-            else
-              echo "No test results found." >> $GITHUB_STEP_SUMMARY
-            fi
 
   wait:
     runs-on: [self-hosted, "${{ inputs.platform }}"]
-    needs: [build-test-image, run-tests]
+    needs: [download-image, run-tests]
     if: success() || failure()
     steps:
       - name: Wait
@@ -181,9 +189,9 @@ jobs:
   # no unused images and stopped containers
   teardown:
     runs-on: [self-hosted, "${{ inputs.platform }}"]
-    needs: [build-test-image, wait]
-    env:
-      image_id: ${{ needs.build-test-image.outputs.image_id }}
+    needs: [download-image, wait]
+    env: 
+      image_id: ${{ needs.download-image.outputs.image_id }}
     if: always()
     steps:
       - name: Stop the containers and remove the image
@@ -191,5 +199,5 @@ jobs:
           docker container stop \
             $(docker ps -q --filter ancestor=${image_id}) || true
           docker container rm --volumes \
-            $(docker ps -qa --filter ancestor=${image_id}) || true
+            $(docker ps -qa --filter ancestor=${image_id}}) || true
           docker image rm ${image_id}
